# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login', blank=True)),
                ('email', models.EmailField(unique=True, max_length=254)),
                ('first_name', models.CharField(max_length=100, verbose_name=b'First Name', blank=True)),
                ('last_name', models.CharField(max_length=100, verbose_name=b'Last Name', blank=True)),
                ('full_name', models.CharField(max_length=200, verbose_name=b'Full Name', blank=True)),
                ('zipcode', models.CharField(max_length=5)),
                ('st_address1', models.CharField(max_length=70, verbose_name=b'Street Address 1', blank=True)),
                ('st_address2', models.CharField(max_length=70, verbose_name=b'Street Address 2', blank=True)),
                ('address_latitude', models.DecimalField(null=True, verbose_name=b'Latitude Coordinate', max_digits=9, decimal_places=6, blank=True)),
                ('address_longitude', models.DecimalField(null=True, verbose_name=b'Longitude Coordinate', max_digits=10, decimal_places=6, blank=True)),
                ('city', models.CharField(max_length=30, blank=True)),
                ('state', models.CharField(max_length=2, blank=True)),
                ('profile_pic_uploaded', models.ImageField(null=True, upload_to=b'profilepics', blank=True)),
                ('imageurl', models.URLField(verbose_name=b'Profile Picture URL', blank=True)),
                ('facebook_id', models.CharField(max_length=40, blank=True)),
                ('facebook_locale', models.CharField(max_length=10, blank=True)),
                ('facebook_email', models.EmailField(max_length=254, blank=True)),
                ('facebook_gender', models.CharField(max_length=15, blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('facebook_verified', models.BooleanField(default=False)),
                ('facebook_first_name', models.CharField(max_length=30, blank=True)),
                ('facebook_last_name', models.CharField(max_length=30, blank=True)),
                ('facebook_response_all', models.CharField(max_length=500, blank=True)),
                ('host', models.BooleanField(default=False)),
                ('hostinterest', models.BooleanField(default=False, verbose_name=b'Interested in Hosting')),
                ('userrating', models.DecimalField(null=True, verbose_name=b'User Rating', max_digits=3, decimal_places=2, blank=True)),
                ('favorscompleted', models.IntegerField(null=True, verbose_name=b'Favors Completed', blank=True)),
                ('favorsrequested', models.IntegerField(null=True, verbose_name=b'Favors Requested', blank=True)),
                ('FBlink', models.URLField(verbose_name=b'Facebook Profile Link', blank=True)),
                ('intro_message', models.CharField(max_length=350, blank=True)),
                ('pickup_time', models.CharField(max_length=150, blank=True)),
                ('account_balance_packages', models.IntegerField(null=True, blank=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name=b'Admin User')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Active User')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name=b'Date Joined', blank=True)),
                ('about_me', models.CharField(max_length=300, verbose_name=b'About Me', blank=True)),
                ('need_storage', models.BooleanField(default=False, verbose_name=b'May Need Storage')),
                ('need_petcare', models.BooleanField(default=False, verbose_name=b'May Need Petcare')),
                ('need_housesitting', models.BooleanField(default=False, verbose_name=b'May Need HouseSitting')),
                ('need_rentals', models.BooleanField(default=False, verbose_name=b'May Need Party/Equipment Rentals')),
                ('need_laundry', models.BooleanField(default=False, verbose_name=b'May Need Laundry')),
                ('need_letin', models.BooleanField(default=False, verbose_name=b'May Need Letting Maintenance Person Into Home')),
                ('need_childcare', models.BooleanField(default=False, verbose_name=b'May Need Childcare')),
                ('need_plantcare', models.BooleanField(default=False, verbose_name=b'May Need Plantcare')),
                ('need_lawn', models.BooleanField(default=False, verbose_name=b'May Need Letting Lawn Care')),
                ('need_carsharing', models.BooleanField(default=False, verbose_name=b'May Need Car Sharing')),
                ('need_housemaint', models.BooleanField(default=False, verbose_name=b'May Need House Maintenance')),
                ('need_autocare', models.BooleanField(default=False, verbose_name=b'May Need Letting Auto Care')),
                ('need_other', models.BooleanField(default=False, verbose_name=b'May Need Other Task/REquests')),
                ('neighborhood', models.CharField(max_length=100, null=True, verbose_name=b'Neighborhood Name', blank=True)),
                ('neighborhood_extended', models.CharField(max_length=100, null=True, verbose_name=b'Broader Neighborhood', blank=True)),
                ('phone_number', models.CharField(max_length=12, null=True, verbose_name=b'Phone Number', blank=True)),
                ('hostrating', models.DecimalField(null=True, verbose_name=b'Host Rating', max_digits=3, decimal_places=2, blank=True)),
                ('services_offered', models.CharField(max_length=250, verbose_name=b'UPDATE TO CHOICES - SERVICES\\q OFFERED', blank=True)),
                ('host_aboutme', models.CharField(max_length=350, verbose_name=b'About Me (Host)', blank=True)),
                ('availability', models.CharField(max_length=250, verbose_name=b'Availability (Write-In)', blank=True)),
                ('whenimhome_days', models.CharField(max_length=250, verbose_name=b"When I'm Home: Days of the Week (Write-In)", blank=True)),
                ('whenimhome_hours', models.CharField(max_length=250, verbose_name=b"When I'm Home: Hours (Write-In)", blank=True)),
                ('address_approx', models.CharField(max_length=100, null=True, verbose_name=b'Approximate Address for Visitors to See', blank=True)),
                ('price_package_per', models.DecimalField(null=True, verbose_name=b'Price Charged Per Package', max_digits=4, decimal_places=2, blank=True)),
                ('price_package_bundle10', models.DecimalField(null=True, verbose_name=b'Price Charged for Bundle of 10 Packages', max_digits=4, decimal_places=2, blank=True)),
                ('price_package_bundle20', models.DecimalField(null=True, verbose_name=b'Price Charged for Bundle of 20 Packages', max_digits=4, decimal_places=2, blank=True)),
                ('price_package_annual', models.DecimalField(null=True, verbose_name=b'Price Charged for Annual Shipmetns', max_digits=5, decimal_places=2, blank=True)),
                ('notifyuser_hostnewtask', models.BooleanField(default=True)),
                ('notifyuser_message', models.BooleanField(default=True)),
                ('notifyuser_packageships', models.BooleanField(default=True)),
                ('notifyuser_deliveryexception', models.BooleanField(default=True)),
                ('notifyuser_packagereceived', models.BooleanField(default=True)),
                ('notifyuser_blocboxnews', models.BooleanField(default=True)),
                ('notifyuser_trackinginfo', models.BooleanField(default=True)),
                ('notifyuser_newhostonblock', models.BooleanField(default=True)),
                ('zipcodes_nearby', models.CharField(max_length=1000, null=True, blank=True)),
                ('zipcodes_nearby_mileradius', models.IntegerField(default=2, null=True, blank=True)),
                ('neighbors_1mileradius', models.CharField(max_length=200, null=True, blank=True)),
                ('neighbors_2mileradius', models.CharField(max_length=400, null=True, blank=True)),
                ('neighbors_3mileradius', models.CharField(max_length=600, null=True, blank=True)),
                ('neighbors_4mileradius', models.CharField(max_length=800, null=True, blank=True)),
                ('neighbors_5mileradius', models.CharField(max_length=1000, null=True, blank=True)),
                ('customchar', models.CharField(max_length=200, null=True, verbose_name=b'Custom Character field to edit later', blank=True)),
                ('customchartwo', models.CharField(max_length=200, null=True, verbose_name=b'Custom Character Field second version', blank=True)),
                ('customcharthree', models.CharField(max_length=100, null=True, verbose_name=b'Custom CharacterField third version', blank=True)),
                ('referredby', models.CharField(max_length=254, null=True, verbose_name=b'Referred By', blank=True)),
                ('Referrals_from_user', models.IntegerField(null=True, verbose_name=b'Referrals Attributed to User - Full Users', blank=True)),
                ('Referrals_from_user_waitlist', models.IntegerField(null=True, verbose_name=b'Referrals Attributed to User - Waitlist Only', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
