# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostConflicts',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date_from', models.DateField(null=True)),
                ('date_to', models.DateField(null=True, blank=True)),
                ('duration', models.IntegerField(null=True, blank=True)),
                ('allday', models.BooleanField(default=False, verbose_name=b'All Day?')),
                ('am', models.BooleanField(default=False, verbose_name=b'AM Conflict')),
                ('pm', models.BooleanField(default=False, verbose_name=b'PM Conflict')),
                ('time_from', models.TimeField(null=True, verbose_name=b'Time: From', blank=True)),
                ('time_to', models.TimeField(null=True, verbose_name=b'Time: To', blank=True)),
                ('datetime_added', models.DateTimeField(default=datetime.datetime.today, null=True, blank=True)),
                ('date_added', models.DateField(default=datetime.date.today, null=True, verbose_name=b'Date Conflict Added by Host', blank=True)),
                ('note', models.CharField(max_length=200, null=True, blank=True)),
                ('label', models.CharField(max_length=50, null=True, blank=True)),
                ('host', models.ForeignKey(related_name='host_conflict', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostWeeklyDefaultSchedule',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('monday_available', models.BooleanField(default=True, verbose_name=b'Mon')),
                ('tuesday_available', models.BooleanField(default=True, verbose_name=b'Tues')),
                ('wednesday_available', models.BooleanField(default=True, verbose_name=b'Weds')),
                ('thursday_available', models.BooleanField(default=True, verbose_name=b'Thur')),
                ('friday_available', models.BooleanField(default=True, verbose_name=b'Fri')),
                ('saturday_available', models.BooleanField(default=True, verbose_name=b'Sat')),
                ('sunday_available', models.BooleanField(default=True, verbose_name=b'Sun')),
                ('default_time1_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 1)', blank=True)),
                ('default_time1_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 1)', blank=True)),
                ('default_time2_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 2)', blank=True)),
                ('default_time2_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 2)', blank=True)),
                ('default_time3_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 3)', blank=True)),
                ('default_time3_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 3)', blank=True)),
                ('default_time4_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 4)', blank=True)),
                ('default_time4_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 4)', blank=True)),
                ('monday_time1_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 1)', blank=True)),
                ('monday_time1_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 1)', blank=True)),
                ('monday_time2_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 2)', blank=True)),
                ('monday_time2_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 2)', blank=True)),
                ('monday_time3_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 3)', blank=True)),
                ('monday_time3_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 3)', blank=True)),
                ('monday_time4_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 4)', blank=True)),
                ('monday_time4_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 4)', blank=True)),
                ('tuesday_time1_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 1)', blank=True)),
                ('tuesday_time1_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 1)', blank=True)),
                ('tuesday_time2_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 2)', blank=True)),
                ('tuesday_time2_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 2)', blank=True)),
                ('tuesday_time3_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 3)', blank=True)),
                ('tuesday_time3_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 3)', blank=True)),
                ('tuesday_time4_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 4)', blank=True)),
                ('tuesday_time4_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 4)', blank=True)),
                ('wednesday_time1_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 1)', blank=True)),
                ('wednesday_time1_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 1)', blank=True)),
                ('wednesday_time2_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 2)', blank=True)),
                ('wednesday_time2_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 2)', blank=True)),
                ('wednesday_time3_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 3)', blank=True)),
                ('wednesday_time3_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 3)', blank=True)),
                ('wednesday_time4_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 4)', blank=True)),
                ('wednesday_time4_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 4)', blank=True)),
                ('thursday_time1_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 1)', blank=True)),
                ('thursday_time1_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 1)', blank=True)),
                ('thursday_time2_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 2)', blank=True)),
                ('thursday_time2_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 2)', blank=True)),
                ('thursday_time3_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 3)', blank=True)),
                ('thursday_time3_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 3)', blank=True)),
                ('thursday_time4_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 4)', blank=True)),
                ('thursday_time4_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 4)', blank=True)),
                ('friday_time1_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 1)', blank=True)),
                ('friday_time1_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 1)', blank=True)),
                ('friday_time2_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 2)', blank=True)),
                ('friday_time2_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 2)', blank=True)),
                ('friday_time3_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 3)', blank=True)),
                ('friday_time3_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 3)', blank=True)),
                ('friday_time4_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 4)', blank=True)),
                ('friday_time4_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 4)', blank=True)),
                ('saturday_time1_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 1)', blank=True)),
                ('saturday_time1_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 1)', blank=True)),
                ('saturday_time2_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 2)', blank=True)),
                ('saturday_time2_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 2)', blank=True)),
                ('saturday_time3_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 3)', blank=True)),
                ('saturday_time3_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 3)', blank=True)),
                ('saturday_time4_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 4)', blank=True)),
                ('saturday_time4_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 4)', blank=True)),
                ('sunday_time1_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 1)', blank=True)),
                ('sunday_time1_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 1)', blank=True)),
                ('sunday_time2_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 2)', blank=True)),
                ('sunday_time2_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 2)', blank=True)),
                ('sunday_time3_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 3)', blank=True)),
                ('sunday_time3_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 3)', blank=True)),
                ('sunday_time4_from', models.TimeField(null=True, verbose_name=b'Default Time Available: From (Window 4)', blank=True)),
                ('sunday_time4_to', models.TimeField(null=True, verbose_name=b'Default Time Available: To (Window 4)', blank=True)),
                ('monday_note', models.CharField(max_length=200, null=True, blank=True)),
                ('tuesday_note', models.CharField(max_length=200, null=True, blank=True)),
                ('wednesday_note', models.CharField(max_length=200, null=True, blank=True)),
                ('thursday_note', models.CharField(max_length=200, null=True, blank=True)),
                ('friday_note', models.CharField(max_length=200, null=True, blank=True)),
                ('saturday_note', models.CharField(max_length=200, null=True, blank=True)),
                ('sunday_note', models.CharField(max_length=200, null=True, blank=True)),
                ('date_schedule_created', models.DateField(default=datetime.date.today, null=True, blank=True)),
                ('date_last_updated', models.DateTimeField(default=datetime.datetime.today, null=True, blank=True)),
                ('host', models.ForeignKey(related_name='host_weeklyschedule', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
    ]
