# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_homebrew', '0003_auto_20150906_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostConflicts_BooleanVersion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('thismonthday1', models.BooleanField(default=False)),
                ('thismonthday2', models.BooleanField(default=False)),
                ('thismonthday3', models.BooleanField(default=False)),
                ('thismonthday4', models.BooleanField(default=False)),
                ('thismonthday5', models.BooleanField(default=False)),
                ('thismonthday6', models.BooleanField(default=False)),
                ('thismonthday7', models.BooleanField(default=False)),
                ('thismonthday8', models.BooleanField(default=False)),
                ('thismonthday9', models.BooleanField(default=False)),
                ('thismonthday10', models.BooleanField(default=False)),
                ('thismonthday11', models.BooleanField(default=False)),
                ('thismonthday12', models.BooleanField(default=False)),
                ('thismonthday13', models.BooleanField(default=False)),
                ('thismonthday14', models.BooleanField(default=False)),
                ('thismonthday15', models.BooleanField(default=False)),
                ('thismonthday16', models.BooleanField(default=False)),
                ('thismonthday17', models.BooleanField(default=False)),
                ('thismonthday18', models.BooleanField(default=False)),
                ('thismonthday19', models.BooleanField(default=False)),
                ('thismonthday20', models.BooleanField(default=False)),
                ('thismonthday21', models.BooleanField(default=False)),
                ('thismonthday22', models.BooleanField(default=False)),
                ('thismonthday23', models.BooleanField(default=False)),
                ('thismonthday24', models.BooleanField(default=False)),
                ('thismonthday25', models.BooleanField(default=False)),
                ('thismonthday26', models.BooleanField(default=False)),
                ('thismonthday27', models.BooleanField(default=False)),
                ('thismonthday28', models.BooleanField(default=False)),
                ('thismonthday29', models.BooleanField(default=False)),
                ('thismonthday30', models.BooleanField(default=False)),
                ('thismonthday31', models.BooleanField(default=False)),
                ('nextmonthday1', models.BooleanField(default=False)),
                ('nextmonthday2', models.BooleanField(default=False)),
                ('nextmonthday3', models.BooleanField(default=False)),
                ('nextmonthday4', models.BooleanField(default=False)),
                ('nextmonthday5', models.BooleanField(default=False)),
                ('nextmonthday6', models.BooleanField(default=False)),
                ('nextmonthday7', models.BooleanField(default=False)),
                ('nextmonthday8', models.BooleanField(default=False)),
                ('nextmonthday9', models.BooleanField(default=False)),
                ('nextmonthday10', models.BooleanField(default=False)),
                ('nextmonthday11', models.BooleanField(default=False)),
                ('nextmonthday12', models.BooleanField(default=False)),
                ('nextmonthday13', models.BooleanField(default=False)),
                ('nextmonthday14', models.BooleanField(default=False)),
                ('nextmonthday15', models.BooleanField(default=False)),
                ('nextmonthday16', models.BooleanField(default=False)),
                ('nextmonthday17', models.BooleanField(default=False)),
                ('nextmonthday18', models.BooleanField(default=False)),
                ('nextmonthday19', models.BooleanField(default=False)),
                ('nextmonthday20', models.BooleanField(default=False)),
                ('nextmonthday21', models.BooleanField(default=False)),
                ('nextmonthday22', models.BooleanField(default=False)),
                ('nextmonthday23', models.BooleanField(default=False)),
                ('nextmonthday24', models.BooleanField(default=False)),
                ('nextmonthday25', models.BooleanField(default=False)),
                ('nextmonthday26', models.BooleanField(default=False)),
                ('nextmonthday27', models.BooleanField(default=False)),
                ('nextmonthday28', models.BooleanField(default=False)),
                ('nextmonthday29', models.BooleanField(default=False)),
                ('nextmonthday30', models.BooleanField(default=False)),
                ('nextmonthday31', models.BooleanField(default=False)),
                ('host', models.ForeignKey(related_name='host_conflicts_boolean', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostConflicts_DateVersion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('thimonthconflict1', models.DateField(blank=True)),
                ('thimonthconflict2', models.DateField(blank=True)),
                ('thimonthconflict3', models.DateField(blank=True)),
                ('thimonthconflict4', models.DateField(blank=True)),
                ('thimonthconflict5', models.DateField(blank=True)),
                ('thimonthconflict6', models.DateField(blank=True)),
                ('thimonthconflict7', models.DateField(blank=True)),
                ('thimonthconflict8', models.DateField(blank=True)),
                ('thimonthconflict9', models.DateField(blank=True)),
                ('thimonthconflict10', models.DateField(blank=True)),
                ('thimonthconflict11', models.DateField(blank=True)),
                ('thimonthconflict12', models.DateField(blank=True)),
                ('thimonthconflict13', models.DateField(blank=True)),
                ('thimonthconflict14', models.DateField(blank=True)),
                ('thimonthconflict15', models.DateField(blank=True)),
                ('thimonthconflict16', models.DateField(blank=True)),
                ('thimonthconflict17', models.DateField(blank=True)),
                ('thimonthconflict18', models.DateField(blank=True)),
                ('thimonthconflict19', models.DateField(blank=True)),
                ('thimonthconflict20', models.DateField(blank=True)),
                ('thimonthconflict21', models.DateField(blank=True)),
                ('thimonthconflict22', models.DateField(blank=True)),
                ('thimonthconflict23', models.DateField(blank=True)),
                ('thimonthconflict24', models.DateField(blank=True)),
                ('thimonthconflict25', models.DateField(blank=True)),
                ('thimonthconflict26', models.DateField(blank=True)),
                ('thimonthconflict27', models.DateField(blank=True)),
                ('thimonthconflict28', models.DateField(blank=True)),
                ('thimonthconflict29', models.DateField(blank=True)),
                ('thimonthconflict30', models.DateField(blank=True)),
                ('thimonthconflict31', models.DateField(blank=True)),
                ('nextmonthconflict1', models.DateField(blank=True)),
                ('nextmonthconflict2', models.DateField(blank=True)),
                ('nextmonthconflict3', models.DateField(blank=True)),
                ('nextmonthconflict4', models.DateField(blank=True)),
                ('nextmonthconflict5', models.DateField(blank=True)),
                ('nextmonthconflict6', models.DateField(blank=True)),
                ('nextmonthconflict7', models.DateField(blank=True)),
                ('nextmonthconflict8', models.DateField(blank=True)),
                ('nextmonthconflict9', models.DateField(blank=True)),
                ('nextmonthconflict10', models.DateField(blank=True)),
                ('nextmonthconflict11', models.DateField(blank=True)),
                ('nextmonthconflict12', models.DateField(blank=True)),
                ('nextmonthconflict13', models.DateField(blank=True)),
                ('nextmonthconflict14', models.DateField(blank=True)),
                ('nextmonthconflict15', models.DateField(blank=True)),
                ('nextmonthconflict16', models.DateField(blank=True)),
                ('nextmonthconflict17', models.DateField(blank=True)),
                ('nextmonthconflict18', models.DateField(blank=True)),
                ('nextmonthconflict19', models.DateField(blank=True)),
                ('nextmonthconflict20', models.DateField(blank=True)),
                ('nextmonthconflict21', models.DateField(blank=True)),
                ('nextmonthconflict22', models.DateField(blank=True)),
                ('nextmonthconflict23', models.DateField(blank=True)),
                ('nextmonthconflict24', models.DateField(blank=True)),
                ('nextmonthconflict25', models.DateField(blank=True)),
                ('nextmonthconflict26', models.DateField(blank=True)),
                ('nextmonthconflict27', models.DateField(blank=True)),
                ('nextmonthconflict28', models.DateField(blank=True)),
                ('nextmonthconflict29', models.DateField(blank=True)),
                ('nextmonthconflict30', models.DateField(blank=True)),
                ('nextmonthconflict31', models.DateField(blank=True)),
                ('host', models.ForeignKey(related_name='host_conflict_dateversion', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostconflicts',
            name='host',
        ),
        migrations.DeleteModel(
            name='HostConflicts',
        ),
    ]
